// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string event_level_15_unlocked = "CgkI84CepMsPEAIQIg"; // <GPGSID>
        public const string event_level_9_unlocked = "CgkI84CepMsPEAIQHA"; // <GPGSID>
        public const string event_level_12_unlocked = "CgkI84CepMsPEAIQHw"; // <GPGSID>
        public const string achievement_50000_points = "CgkI84CepMsPEAIQBQ"; // <GPGSID>
        public const string achievement_10000_points = "CgkI84CepMsPEAIQBA"; // <GPGSID>
        public const string event_level_8_unlocked = "CgkI84CepMsPEAIQGw"; // <GPGSID>
        public const string event_level_5_unlocked = "CgkI84CepMsPEAIQDA"; // <GPGSID>
        public const string event_level_16_unlocked = "CgkI84CepMsPEAIQIw"; // <GPGSID>
        public const string achievement_first_15_sets_of_3_planes_at_once = "CgkI84CepMsPEAIQFQ"; // <GPGSID>
        public const string event_level_13_unlocked = "CgkI84CepMsPEAIQIA"; // <GPGSID>
        public const string leaderboard_level_4_highscores = "CgkI84CepMsPEAIQDw"; // <GPGSID>
        public const string leaderboard_level_3_highscores = "CgkI84CepMsPEAIQDg"; // <GPGSID>
        public const string achievement_first_30_planes = "CgkI84CepMsPEAIQCg"; // <GPGSID>
        public const string leaderboard_level_6_highscores = "CgkI84CepMsPEAIQEQ"; // <GPGSID>
        public const string achievement_first_30_sets_of_2_planes_at_once = "CgkI84CepMsPEAIQEg"; // <GPGSID>
        public const string event_level_4_unlocked = "CgkI84CepMsPEAIQCQ"; // <GPGSID>
        public const string achievement_100000_points = "CgkI84CepMsPEAIQBg"; // <GPGSID>
        public const string achievement_first_10_sets_of_2_planes_at_once = "CgkI84CepMsPEAIQCw"; // <GPGSID>
        public const string achievement_first_3_sets_of_4_planes_at_a_time = "CgkI84CepMsPEAIQGQ"; // <GPGSID>
        public const string event_level_6_unlocked = "CgkI84CepMsPEAIQGA"; // <GPGSID>
        public const string leaderboard_level_1_highscores = "CgkI84CepMsPEAIQCA"; // <GPGSID>
        public const string achievement_first_2_sets_of_4_planes_at_once = "CgkI84CepMsPEAIQFw"; // <GPGSID>
        public const string achievement_5000_points = "CgkI84CepMsPEAIQAw"; // <GPGSID>
        public const string event_level_10_unlocked = "CgkI84CepMsPEAIQHQ"; // <GPGSID>
        public const string leaderboard_level_5_highscores = "CgkI84CepMsPEAIQEA"; // <GPGSID>
        public const string achievement_1000_points = "CgkI84CepMsPEAIQAg"; // <GPGSID>
        public const string leaderboard_level_2_highscores = "CgkI84CepMsPEAIQDQ"; // <GPGSID>
        public const string event_level_7_unlocked = "CgkI84CepMsPEAIQGg"; // <GPGSID>
        public const string event_level_14_unlocked = "CgkI84CepMsPEAIQIQ"; // <GPGSID>
        public const string achievement_first_100_planes = "CgkI84CepMsPEAIQEw"; // <GPGSID>
        public const string event_level_11_unlocked = "CgkI84CepMsPEAIQHg"; // <GPGSID>
        public const string leaderboard_best_scores = "CgkI84CepMsPEAIQBw"; // <GPGSID>
        public const string achievement_first_5_sets_of_3_planes_at_once = "CgkI84CepMsPEAIQFA"; // <GPGSID>

}

